- name: Expense project setup
  hosts: all
  become: true
  roles:
    - "{{ service_name }}" # play level roles


##original way or classic way
#- hosts: webservers
#  roles:
#    - common
#    - webservers