- name: Frontend setup
  hosts: all
  become: true
  tasks:
    - name: Install Nginx
      ansible.builtin.dnf:
        name: nginx
        state: installed

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: expense.conf
        dest: /etc/nginx/default.d/expense.conf

    - name: Delete existing app content
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: Download and extract app content
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/frontend.zip
        dest: /usr/share/nginx/html

    - name: Enable and restart Nginx services
      ansible.builtin.systemd_service:
        name: nginx
        enabled: true
        state: restarted
