- name: Disable default version of nodeJS
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Enable nodeJS18 version
  ansible.builtin.shell: dnf module enable nodejs:18 -y

- name: Install nodeJS
  ansible.builtin.dnf:
    name: nodejs
    state: installed

- name: Configure backend service
  ansible.builtin.copy:
    src: backend.service
    dest: /etc/systemd/system/backend.service

- name: Adding application user
  ansible.builtin.user:
    name: expense

- name: App Pre-Requisites
  ansible.builtin.include_role:
    name: common
    tasks_from: app_prereq

- name: Install application dependencies
  community.general.npm:
    path: /app

- name: Reloading SystemD and start backend service
  ansible.builtin.systemd.service:
    name: backend
    enabled: true
    state: restarted

- name: Install MySQL & python library for Mysql
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: installed
  loop:
    - mysql
    - python3-PyMySQL

- name: Load schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/schema/backend.sql
    login_user: root
    login_password: ExpenseApp@1
    login_host: mysql-dev.aquireawsdevops.online