#dnf install nginx -y
- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: App Pre-Requisites
  ansible.builtin.include_role:
    name: common
    tasks_from: app_prereq

#cp expense.conf /etc/nginx/default.d/expense.conf
- name: Copy config file
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf
#systemctl enable nginx
#systemctl start nginx
- name: Enable and start nginx services
  ansible.builtin.systemd_service:
    name: nginx
    state: started
    enabled: true