#dnf install nginx
- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

#common
- name: App Pre-Requisites
  ansible.builtin.include_role:
    name: common
    tasks_from: app_prereq

#cp  expense.conf /etc/nginx/default.d/expense.conf
- name: Copy conf files
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf
#systemctl enable nginx
#systemctl start nginx
- name: Enable and restart nginx service
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted
    enabled: true