#dnf module disable mysql -y
- name: Disable default version of mysql
  ansible.builtin.shell: dnf module disable mysql -y
#/etc/yum.repos.d/mysql.repo
- name: Copy repo files
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo
#dnf install mysql-community-server -y
- name: Install mysql community server
  ansible.builtin.dnf:
    name: mysql-community-server
    state: present
#systemctl enable mysqld
- name: Enable and restart mysqld service
  ansible.builtin.systemd_service:
    name: mysqld
    enabled: true
    state: restarted
#mysql_secure_installation --set-root-pass ExpenseApp@1
- name: Set root password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass "{{ lookup('amazon.aws.aws_ssm','dev.mysql.root_password', region='us-east-1') }}"