format_version: 10
pipelines:
  deploy: #name of the pipeline
    group: defaultGroup  # we can also create a group, let it be in default group.
    label_template: "foo-1.0-${COUNT}" #when we run the job go to history. Here are count instead of count we can add prefix
    lock_behavior: true
    display_order: -1 #default value
    materials:
      ansible:
        git: https://github.com/Sumanth990/expense-ansible.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - dev:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            deployment:
              timeout: 0
              tasks:
                - exec:
                    command: ls -l
                    run_if: passed
